services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - "5080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    networks:
      - devops
  jenkins-slave:
    image: jenkins/agent:latest
    container_name: jenkins-slave
    init: true
    group_add:
      - 986
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/homebrew/bin/docker-compose:/usr/local/bin/docker-compose
      - /Users/juliany/agente.jk:/home/jenkins/agent
    working_dir: /home/jenkins/agent
    command: >
      java -jar agent.jar -workDir /home/jenkins/agent -url http://jenkins:8080/ -name slave -webSocket -secret 3c9c543d07366007830265af9d31261a92f4825668e549233fa35355ae1d02e2
    depends_on:
      - jenkins
    networks:
      - devops
volumes:
  jenkins_home:
  jenkins-slave_home:


networks:
  devops:
    driver: bridge
