    services:
      jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        ports:
          - "5080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
        environment:
          - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

    volumes:
      jenkins_home: