apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-micro
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-micro
  template:
    metadata:
      labels:
        app: demo-micro
    spec:
      containers:
        - name: app
          image: docker.io/julanih/demo-micro:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0"
          redinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      #imagePullSecrets:
      #  - name: regcred