apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-micro
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-micro
  template:
    metadata:
      labels:
        app: demo-micro
    spec:
      containers:
        - name: app
          image: docker.io/julanih/demo-micro:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      # Para repositorios privados, habilitar:
      # imagePullSecrets:
      #   - name: regcred