apiVersion: v1
kind: Service
metadata:
  name: demo-micro
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-micro
  ports:
    - name: http
      port: 80
      targetPort: 8888
      nodePort: 30080