# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Find jar
      run: |
        ls-al target/*.jar
    
    - name: Build image
      run: |
        docker build -t julanih/ms-agosto-01:v1 .
    
    - name: Docker login
      run: |
        docker login -u ${{ secrets.USER_HUB }} -p ${{ secrets.PASS_HUB }}
    - name: Push image
      run: |
        docker push julanih/ms-agosto-01:v1
